name: uber_clone
description: تطبيق مشابه لأوبر يتيح طلب رحلات في القاهرة والجيزة
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_maps_flutter: ^2.5.0
  provider: ^6.1.5
  geolocator: ^10.1.0
  flutter_polyline_points: ^1.0.0
  http: ^0.13.5
  shared_preferences: ^2.0.15
  image_picker: ^0.8.6
  flutter_rating_bar: ^4.0.1
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/
    - lib/assets/map_sample.png
    - assets/images/
    - assets/icons/
  # fonts:
  #   - family: Cairo
  #     fonts:
  #       - asset: assets/fonts/Cairo-Regular.ttf
  #       - asset: assets/fonts/Cairo-Bold.ttf
  #         weight: 700