name: uber_clone
description: تطبيق مشابه لأوبر يتيح طلب رحلات في القاهرة والجيزة
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_maps_flutter: ^2.2.5
  provider: ^6.0.5
  geolocator: ^9.0.2
  flutter_polyline_points: ^1.0.0
  http: ^0.13.5
  shared_preferences: ^2.0.15
  image_picker: ^0.8.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # إذا لم تكن هذه المجلدات موجودة، احذف أو علق الأسطر التالية
assets:
  #   - assets/images/
  #   - assets/icons/
  # fonts:
  #   - family: Cairo
  #     fonts:
  #       - asset: assets/fonts/Cairo-Regular.ttf
  #       - asset: assets/fonts/Cairo-Bold.ttf
  #         weight: 700